In [1]:
# this is for practising linear algebra
import numpy as np

In [2]:
A=np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

In [3]:
# Multiply the matrices
C = np.dot(A, B)

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("A x B =\n", C)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
A x B =
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
